
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author noel
 */
public class RegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm() {
        initComponents();
    }

    Connection con;
    Statement st;
    PreparedStatement pst;
    ResultSet rs;

    public void Connection() throws SQLException {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        lName = new javax.swing.JTextField();
        mName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bDay = new javax.swing.JTextField();
        aAge = new javax.swing.JTextField();
        aAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rRegistration = new javax.swing.JButton();
        cbVotingstatus = new javax.swing.JComboBox<>();
        cbGender = new javax.swing.JComboBox<>();

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("BARANGAY INFORMATION SYSTEMS");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(729, 524));
        setMinimumSize(new java.awt.Dimension(729, 524));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 0, 0);

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Barangay Registration Form");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("BARANGAY INFORMATION SYSTEMS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(188, 188, 188))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(238, 238, 238))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 728, 100);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(730, 440));
        jPanel2.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("First Name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(320, 40, 80, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Last Name");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(320, 70, 110, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Middle Name");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(320, 100, 130, 20);

        fName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameActionPerformed(evt);
            }
        });
        jPanel2.add(fName);
        fName.setBounds(460, 40, 170, 22);

        lName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameActionPerformed(evt);
            }
        });
        jPanel2.add(lName);
        lName.setBounds(460, 70, 170, 22);

        mName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNameActionPerformed(evt);
            }
        });
        jPanel2.add(mName);
        mName.setBounds(460, 100, 170, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Gender");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(320, 270, 90, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Address");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(320, 210, 90, 20);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Birthdate ");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(320, 180, 110, 20);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Age ");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(320, 240, 70, 20);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Voters Status ");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(320, 130, 130, 20);
        jPanel2.add(bDay);
        bDay.setBounds(460, 180, 169, 22);

        aAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aAgeActionPerformed(evt);
            }
        });
        jPanel2.add(aAge);
        aAge.setBounds(460, 240, 169, 22);

        aAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aAddressActionPerformed(evt);
            }
        });
        jPanel2.add(aAddress);
        aAddress.setBounds(460, 210, 169, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setText("Example: MM/DD/YYYY");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(460, 160, 126, 16);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Tip:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(390, 380, 20, 20);

        jLabel11.setText("Be a responsible citizen at all times!");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(390, 400, 190, 20);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\noel\\Downloads\\Bukidnon-Davao_Road,_Calinan_(Davao_City;_08-22-2023).jpg")); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(-300, 0, 550, 440);

        rRegistration.setText("REGISTRATION");
        rRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rRegistrationActionPerformed(evt);
            }
        });
        jPanel2.add(rRegistration);
        rRegistration.setBounds(460, 320, 110, 23);

        cbVotingstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registered", "Not Registered" }));
        jPanel2.add(cbVotingstatus);
        cbVotingstatus.setBounds(460, 130, 170, 22);

        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Non-Binary" }));
        cbGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGenderActionPerformed(evt);
            }
        });
        jPanel2.add(cbGender);
        cbGender.setBounds(460, 270, 170, 22);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 100, 730, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aAgeActionPerformed

    private void mNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mNameActionPerformed

    private void fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameActionPerformed

    private void lNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameActionPerformed

    private void aAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aAddressActionPerformed

    private void rRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rRegistrationActionPerformed
        // Retrieve input values
        String firstname = fName.getText();
        String lastname = lName.getText();
        String middlename = mName.getText();
        String votingstatus = (String) cbVotingstatus.getSelectedItem();
        String address = aAddress.getText();
        String age = aAge.getText();
        String gender = (String) cbGender.getSelectedItem();

// Validate inputs
        if (firstname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "First Name cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (lastname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Last Name cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (middlename.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Middle Name cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (address.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Address cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (age.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Age cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

// Define the file path
        String documentsPath = System.getProperty("user.home") + File.separator + "Documents";
        File userFolder = new File(documentsPath + File.separator + "RegisteredResidents");

// Create directory if it does not exist
        if (!userFolder.exists()) {
            userFolder.mkdirs();
        }

// Write data to file
        try {
            FileWriter writer = new FileWriter(userFolder.getAbsolutePath() + File.separator + "residents.txt", true);
            writer.write(firstname + "," + lastname + "," + middlename + "," + votingstatus + "," + address + "," + age + "," + gender + "\n");
            writer.close();
            JOptionPane.showMessageDialog(this, "Resident registered successfully!");
            this.dispose(); //closes the window
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_rRegistrationActionPerformed

    private void cbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aAddress;
    private javax.swing.JTextField aAge;
    private javax.swing.JTextField bDay;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JComboBox<String> cbVotingstatus;
    private javax.swing.JTextField fName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lName;
    private javax.swing.JTextField mName;
    private javax.swing.JButton rRegistration;
    // End of variables declaration//GEN-END:variables
}
